### PR TITLE
docs: Add example of applying policy by guest's hostname

### PR DESCRIPTION
**Pull request by inflatador**
Show how to set a variable based on guest
properties, and how to conditionally apply
policy based on the guest property.

Addresses [this issue](https://github.com/oVirt/mom/issues/26)

### CODE REVIEW

**Review by nyoxi — APPROVED** [review]

**Comment by nyoxi** [comment]
Thanks for the patch. Unfortunately your commit is missing `Signed-of-by` line. Once that is added your patch can be merged.

**Comment by inflatador** [comment]
@nyoxi Thanks for your patience! I added the requested `Signed-off-by` line, let me know you need anything else.

**Comment by nyoxi** [comment]
@inflatador hello, unfortunately CI is complaining. First issue is that the DCO check is still failing. Author of the commit is set to `Private User` but the SoB line contains your name. 

Second issue is with our GitHub actions. I have opened #28 to address this but I run into another issue.

**Comment by nyoxi** [comment]
CI is fixed. Please don't forget to rebase once you fix your issue with DCO.

**Pull request merged**
